name: Checks

on:
    push:
        branches:
            - main
    pull_request:
        types: [opened, reopened, synchronize]

jobs:
    cs_fixers:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
              with:
                  ref: ${{ github.head_ref }}
                  fetch-depth: 50
                  token: ${{ secrets.GITHUB_TOKEN }}
            - run: |
                  git fetch origin master

            - name: Install prettier
              uses: actions/setup-node@v2
              with:
                  node-version: '12'

            - name: Run prettier
              run: |
                  npm install -g prettier@
                  git diff --name-only --diff-filter=ACMRTUXB "origin/${{ github.base_ref }}" | xargs prettier --write --

            - uses: stefanzweifel/git-auto-commit-action@v4
              with:
                  commit_message: Apply CS fixes

    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Test using Jest
              uses: actions/setup-node@v2
              with:
                node-version: '12'
            - run: yarn install
            - run: yarn test
