name: Checks

on:
    push:
        branches:
            - main
    pull_request:
        types: [opened, reopened, synchronize]

jobs:
    cs_fixers:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
              with:
                ref: ${{ github.head_ref }}

            - name: Install prettier
              uses: actions/setup-node@v2
              with:
                node-version: '12'

            - name: Prettify code
              uses: creyD/prettier_action@v3.3
              with:
                prettier_options: --write **/*.{js,md}
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

            - uses: stefanzweifel/git-auto-commit-action@v4
              with:
                  commit_message: Apply CS fixes

    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Test using Jest
              uses: actions/setup-node@v2
              with:
                node-version: '12'
            - run: yarn install
            - run: yarn test
